#!/usr/bin/env python3
"""Disk-persisted scheduler for unattended SW_MMO_Prototype work.

This is adapted from the durable-loop tooling in C:\\SW_MUSH_night, but kept
standalone and agent-command agnostic. The durable part is Windows Task
Scheduler: persisted tasks, skipped overlapping runs, start-when-available, and
an execution timeout. The agent command is explicit because Codex Desktop is not
guaranteed to expose a stable headless CLI on every machine.

Typical dry run:
  python tools/durable_loop.py arm --in 300 --dry-run

Benign scheduler self-test:
  python tools/durable_loop.py arm --in 60 --test-fire

Real unattended use requires a working headless command:
  python tools/durable_loop.py arm --every 30 --agent-command "codex exec -"
"""
from __future__ import annotations

import argparse
import datetime as _dt
import os
import subprocess
import sys
from pathlib import Path

DEFAULT_NAME = "SWMMOPrototype-DurableLoop"
DEFAULT_WORKDIR = "C:/Users/btgla/Documents/Codex/2026-06-14/i-d-like-you-to-create/outputs/SW_MMO_Prototype"
DEFAULT_AGENT_COMMAND = "codex exec -"
_HOME = Path(os.environ.get("USERPROFILE") or Path.home())
STATE_ROOT = _HOME / ".codex" / "durable_loop" / "SW_MMO_Prototype"


def default_prompt(workdir: str) -> str:
	return (
		"Autonomous SW_MMO_Prototype durable resume. You are a fresh headless "
		"agent session with little or no prior chat context. Work only in "
		f"{workdir}. Treat C:\\SW_MUSH as read-only reference. The goal is WEG "
		"Star Wars D6 faithfulness translated into a fun 3D/2.5D MMO, not a "
		"one-to-one MUSH port. First read README.md, docs/WEG_FIDELITY.md, "
		"docs/REALTIME_D6_TRANSLATION.md, docs/MOS_EISLEY_SLICE.md, and "
		"docs/COMBAT_SOURCE_TRACE.md. Then inspect current files, implement one "
		"bounded forward slice, update tests/docs, run .\\tools\\check_project.ps1 "
		"in the foreground, and stop after a clean checkpoint or a real blocker. "
		"Do not wait passively for notifications. Do not touch SW_MUSH."
	)


def _iso(dt: _dt.datetime) -> str:
	return dt.strftime("%Y-%m-%dT%H:%M:%S")


def build_launcher(
	workdir: str,
	prompt_file: str,
	log_dir: str,
	agent_command: str,
	raw_action: str | None = None,
) -> str:
	head = (
		"@echo off\r\n"
		"REM SW_MMO_Prototype durable-loop launcher. Generated by tools\\durable_loop.py.\r\n"
		"setlocal\r\n"
		"for /f %%I in ('powershell -NoProfile -Command "
		"\"Get-Date -Format yyyyMMdd_HHmmss\"') do set \"TS=%%I\"\r\n"
		f'cd /d "{workdir}"\r\n'
	)
	if raw_action is not None:
		body = f'{raw_action} > "{log_dir}\\run_%TS%.log" 2>&1\r\n'
	else:
		body = f'type "{prompt_file}" | {agent_command} > "{log_dir}\\run_%TS%.log" 2>&1\r\n'
	return head + body + "endlocal\r\n"


def build_task_xml(
	launcher_path: str,
	*,
	start_dt: _dt.datetime,
	every_minutes: int | None = None,
	description: str = "",
	exec_time_limit: str = "PT2H",
) -> str:
	if every_minutes is not None:
		repetition = (
			"      <Repetition>\n"
			f"        <Interval>PT{int(every_minutes)}M</Interval>\n"
			"        <StopAtDurationEnd>false</StopAtDurationEnd>\n"
			"      </Repetition>\n"
		)
	else:
		repetition = ""

	return (
		'<?xml version="1.0" encoding="UTF-16"?>\n'
		'<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\n'
		"  <RegistrationInfo>\n"
		"    <Author>SW_MMO_Prototype durable_loop</Author>\n"
		f"    <Description>{description}</Description>\n"
		"  </RegistrationInfo>\n"
		"  <Triggers>\n"
		"    <TimeTrigger>\n"
		f"      <StartBoundary>{_iso(start_dt)}</StartBoundary>\n"
		f"{repetition}"
		"      <Enabled>true</Enabled>\n"
		"    </TimeTrigger>\n"
		"  </Triggers>\n"
		"  <Principals>\n"
		'    <Principal id="Author">\n'
		"      <LogonType>InteractiveToken</LogonType>\n"
		"      <RunLevel>LeastPrivilege</RunLevel>\n"
		"    </Principal>\n"
		"  </Principals>\n"
		"  <Settings>\n"
		"    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n"
		"    <StartWhenAvailable>true</StartWhenAvailable>\n"
		"    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n"
		"    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n"
		"    <AllowHardTerminate>true</AllowHardTerminate>\n"
		f"    <ExecutionTimeLimit>{exec_time_limit}</ExecutionTimeLimit>\n"
		"    <Enabled>true</Enabled>\n"
		"  </Settings>\n"
		'  <Actions Context="Author">\n'
		"    <Exec>\n"
		"      <Command>cmd.exe</Command>\n"
		f'      <Arguments>/c "{launcher_path}"</Arguments>\n'
		"    </Exec>\n"
		"  </Actions>\n"
		"</Task>\n"
	)


def _task_dir(name: str) -> Path:
	return STATE_ROOT / name


def _run(cmd: list[str]) -> subprocess.CompletedProcess:
	return subprocess.run(cmd, capture_output=True, text=True)


def _resolve_start(args) -> tuple[_dt.datetime, int | None]:
	now = _dt.datetime.now()
	if args.every is not None:
		return now + _dt.timedelta(seconds=30), args.every
	if args.in_seconds is not None:
		return now + _dt.timedelta(seconds=args.in_seconds), None
	if args.at is not None:
		try:
			return _dt.datetime.strptime(args.at, "%Y-%m-%d %H:%M"), None
		except ValueError as exc:
			raise ValueError("--at must be 'YYYY-MM-DD HH:MM'") from exc
	raise ValueError("provide one of --every, --in, or --at")


def cmd_arm(args) -> int:
	try:
		start, every = _resolve_start(args)
	except ValueError as exc:
		print(f"error: {exc}", file=sys.stderr)
		return 2

	workdir = str(Path(args.workdir).resolve())
	tdir = _task_dir(args.name)
	log_dir = tdir / "logs"
	prompt_file = tdir / "prompt.txt"
	launcher = tdir / "launcher.cmd"
	xml_file = tdir / "task.xml"

	if args.prompt:
		prompt = args.prompt
	elif args.prompt_file:
		prompt = Path(args.prompt_file).read_text(encoding="utf-8")
	else:
		prompt = default_prompt(workdir)

	raw_action = None
	if args.test_fire:
		raw_action = "echo durable_loop test fire %TS% & echo OK"

	launcher_text = build_launcher(
		workdir,
		str(prompt_file),
		str(log_dir),
		args.agent_command,
		raw_action=raw_action,
	)
	desc = (
		f"SW_MMO_Prototype durable loop "
		f"({'every ' + str(every) + 'm' if every else 'one-shot'}); workdir {workdir}"
	)
	xml_text = build_task_xml(str(launcher), start_dt=start, every_minutes=every, description=desc)

	if args.dry_run:
		print(f"# would register task {args.name!r} starting {_iso(start)}")
		print("=== launcher.cmd ===\n" + launcher_text)
		print("=== task.xml ===\n" + xml_text)
		return 0

	if os.name != "nt":
		print("error: registering uses Windows Task Scheduler; use --dry-run elsewhere.", file=sys.stderr)
		return 2

	log_dir.mkdir(parents=True, exist_ok=True)
	prompt_file.write_text(prompt, encoding="utf-8")
	launcher.write_text(launcher_text, encoding="utf-8", newline="")
	xml_file.write_text(xml_text, encoding="utf-16")

	res = _run(["schtasks", "/create", "/tn", args.name, "/xml", str(xml_file), "/f"])
	sys.stdout.write(res.stdout)
	sys.stderr.write(res.stderr)
	if res.returncode != 0:
		return res.returncode
	print(f"\narmed: {args.name} first fire {_iso(start)}")
	print(f"  launcher: {launcher}")
	print(f"  logs:     {log_dir}")
	return 0


def cmd_list(args) -> int:
	res = _run(["schtasks", "/query", "/tn", args.name, "/v", "/fo", "LIST"])
	if res.returncode != 0:
		print(f"(no task named {args.name!r} registered)")
		return 0
	for line in res.stdout.splitlines():
		if any(key in line for key in ("TaskName:", "Status:", "Next Run Time:", "Last Run Time:", "Last Result:")):
			print(line.strip())
	return 0


def cmd_disarm(args) -> int:
	res = _run(["schtasks", "/delete", "/tn", args.name, "/f"])
	sys.stdout.write(res.stdout)
	sys.stderr.write(res.stderr)
	return res.returncode


def cmd_status(args) -> int:
	log_dir = _task_dir(args.name) / "logs"
	logs = sorted(log_dir.glob("run_*.log"), key=lambda p: p.stat().st_mtime) if log_dir.is_dir() else []
	if not logs:
		print(f"(no run logs yet under {log_dir})")
		return 0
	latest = logs[-1]
	print(f"=== latest run log: {latest.name} ===")
	text = latest.read_text(encoding="utf-8", errors="replace")
	print("\n".join(text.splitlines()[-args.tail:]))
	return 0


def build_parser() -> argparse.ArgumentParser:
	parser = argparse.ArgumentParser(description="Windows Task Scheduler durable loop for SW_MMO_Prototype.")
	sub = parser.add_subparsers(dest="cmd", required=True)

	arm = sub.add_parser("arm", help="register a scheduled durable run")
	group = arm.add_mutually_exclusive_group()
	group.add_argument("--every", type=int, metavar="MIN", help="recurring interval")
	group.add_argument("--in", dest="in_seconds", type=int, metavar="SEC", help="one-shot delay")
	group.add_argument("--at", metavar="'YYYY-MM-DD HH:MM'", help="one-shot wall-clock time")
	arm.add_argument("--name", default=DEFAULT_NAME)
	arm.add_argument("--workdir", default=DEFAULT_WORKDIR)
	arm.add_argument("--agent-command", default=DEFAULT_AGENT_COMMAND)
	arm.add_argument("--prompt", default=None)
	arm.add_argument("--prompt-file", default=None)
	arm.add_argument("--dry-run", action="store_true")
	arm.add_argument("--test-fire", action="store_true", help="write a benign log instead of launching the agent")
	arm.set_defaults(func=cmd_arm)

	for name, fn, help_text in (
		("list", cmd_list, "show the registered task"),
		("disarm", cmd_disarm, "delete the registered task"),
		("status", cmd_status, "tail the latest run log"),
	):
		cmd = sub.add_parser(name, help=help_text)
		cmd.add_argument("--name", default=DEFAULT_NAME)
		if name == "status":
			cmd.add_argument("--tail", type=int, default=30)
		cmd.set_defaults(func=fn)

	return parser


def main(argv: list[str] | None = None) -> int:
	args = build_parser().parse_args(argv)
	return args.func(args)


if __name__ == "__main__":
	sys.exit(main())
